Repository Chizaruu/recipetineats, pull requests merged in 2022-05, with the labels that each got.

#1 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: enhancement

#2 Feature/create-app
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: enhancement

#3 Added devDependency -> nth-check >=2.0.1
  package.json
Labels: enhancement

#4 feature/first-section
  public/images/facebook-icon.png
  public/images/instagram-icon.PNG
  public/images/pinterest-icon.PNG
  public/images/reciptineats-icon.PNG
  public/images/search-icon.png
  public/images/youtube-icon.PNG
  src/App.css
  src/App.js
  src/App.module.scss
  src/components/first-section/Card/Card.jsx
  src/components/first-section/Card/Card.module.scss
  src/components/first-section/Card/index.js
  src/components/first-section/SocialButton/SocialButton.jsx
  src/components/first-section/SocialButton/SocialButton.module.scss
  src/components/first-section/SocialButton/index.js
  src/container/first-section/Header/Header.jsx
  src/container/first-section/Header/Header.module.scss
  src/container/first-section/Header/index.js
  src/container/first-section/Nav/Nav.jsx
  src/container/first-section/Nav/Nav.module.scss
  src/container/first-section/Nav/index.js
Labels: enhancement

#6 (JSpeechY) I created the second section with the cards on the website
  package-lock.json
  src/App.js
  src/components/CardSecondSection/Card.jsx
  src/components/CardSecondSection/Card.module.scss
  src/components/CardSecondSection/index.js
  src/containers/CardListSecondSection/CardListSecondSection.jsx
  src/containers/CardListSecondSection/CardListSecondSection.module.scss
  src/containers/CardListSecondSection/index.js
  src/data/recipes.js
Labels: enhancement

#8 GitHub/readme
  README.md
Labels: documentation

#7 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#11 enhancement/header-background-fix
  src/container/first-section/Header/Header.module.scss
Labels: enhancement

#9 Refactored Folder Structure, Removed unused code (firstsection/Card), Added alt text to Card.jsx img tag, Updated imports and exports.
  src/App.js
  src/components/Card/Card.jsx
  src/components/Card/Card.module.scss
  src/components/Card/index.js
  src/components/CardSecondSection/index.js
  src/components/SocialButton/SocialButton.jsx
  src/components/SocialButton/SocialButton.module.scss
  src/components/SocialButton/index.js
  src/components/first-section/Card/Card.jsx
  src/components/first-section/Card/Card.module.scss
  src/containers/CardList/CardList.jsx
  src/containers/CardList/CardList.module.scss
  src/containers/CardList/index.js
  src/containers/CardListSecondSection/CardListSecondSection.jsx
  src/containers/CardListSecondSection/index.js
  src/containers/Header/Header.jsx
  src/containers/Header/Header.module.scss
  src/containers/Header/index.js
  src/containers/Nav/Nav.jsx
  src/containers/Nav/Nav.module.scss
  src/containers/Nav/index.js
Labels: enhancement

#12 Create build-deploy.yml
  .github/workflows/build-deploy.yml
Labels: enhancement

#13 Update build-deploy.yml
  .github/workflows/build-deploy.yml
Labels: bug, enhancement

#14 Delete App.test.js
  src/App.test.js
Labels: bug

#15 Update package.json
  package.json
Labels: enhancement

#16 Update build-deploy.yml
  .github/workflows/build-deploy.yml
Labels: bug

#17 Changed title in index.html
  public/index.html
Labels: enhancement

#18 created the third sections
  src/App.js
  src/App.module.scss
  src/components/Button/Button.jsx
  src/components/Button/Button.module.scss
  src/components/Button/index.js
  src/components/Card/Card.jsx
  src/components/Card/Card.module.scss
  src/components/SmallCards/SmallCards.jsx
  src/components/SmallCards/SmallCards.module.scss
  src/components/SmallCards/index.js
  src/containers/ChickenRecipes/ChickenRecipes.jsx
  src/containers/ChickenRecipes/ChickenRecipes.module.scss
  src/containers/ChickenRecipes/index.js
  src/containers/Collections/Collections.jsx
  src/containers/Collections/Collections.module.scss
  src/containers/Collections/index.js
  src/containers/HaveABrowse/HaveABrowse.jsx
  src/containers/HaveABrowse/HaveABrowse.module.scss
  src/containers/HaveABrowse/index.js
  src/containers/Section/Section.jsx
  src/containers/Section/Section.module.scss
  src/containers/Section/index.js
  src/containers/Subscribe/Subscribe.jsx
  src/containers/Subscribe/Subscribe.module.scss
  src/containers/Subscribe/index.js
Labels: enhancement
